### ISSUE TITLE
I would like to deploy my blogging site using this

### ISSUE THREAD

**Issue by daranil** [fortysev-en/django-bootstrap-blogging-template-pro#3]
Hi @fortysev-en 

I am looking to deploy blogging site. when I came across your repo, I see it covers the required features for deploying a blogging site. So, I would like to know is the code deployment ready. If possible can you freelance for me to fork the repo, do necessary changes if any needed and make it deploy ready and deploy the site.

**Comment by fortysev-en** [comment]
Sure, I can help you with that. Let's discuss this on Discord. Send me a message on `fortyseven#1540`

**Comment by daranil** [comment]
Ok

**Comment by daranil** [comment]
I sent you friend request on discord. My discord anil#9119
